version: '3.7'
services:
  postgres:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: nexus
      POSTGRES_USER: nexus
    networks:
    - nexus-benchmark-network
    tmpfs:
    - /var/lib/postgresql/data:rw
  prisma:
    image: prismagraphql/prisma:1.29.2
    restart: always
    depends_on:
    - postgres
    volumes:
    - ./prisma/:/app/prisma/
    networks:
    - nexus-benchmark-network
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: nexus
            password: nexus
            migrations: true
  benchmark:
    image: nexus-benchmark:dev
    depends_on:
    - prisma
    volumes:
    - ./prisma/:/app/prisma/
    networks:
    - nexus-benchmark-network
    entrypoint:
    - npx
    - prisma
    - deploy
networks:
  nexus-benchmark-network:
    name: nexus-benchmark-network
    driver: bridge
